# Generated by Django 5.1 on 2024-09-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeddingBookings',
            new_name='WeddingBooking',
        ),
    ]
