# Generated by Django 5.1 on 2024-09-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_priestprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priestprofile',
            name='photo',
            field=models.ImageField(default='sfbc/profiles/default.jpg', upload_to='sfbc/profiles/'),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Parish Priest'), ('2', 'Assistant Parish Priest'), ('3', 'Priest in Residence'), ('4', 'Catechist'), ('5', 'Seminarian'), ('6', 'Admin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='title',
            field=models.CharField(choices=[('1', 'Very Rev. Fr.'), ('2', 'Rev. Fr.'), ('3', 'Catechist'), ('4', 'Brother'), ('5', 'Deacon'), ('6', 'Rev.')], max_length=50),
        ),
    ]
