# Generated by Django 5.1 on 2024-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_priestprofile_photo_alter_priestprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priestprofile',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
