# Generated by Django 5.1 on 2024-09-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_priestprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priestprofile',
            name='position',
            field=models.CharField(choices=[('1', 'Parish Priest'), ('2', 'Assistant Parish Priest'), ('3', 'Priest in Residence'), ('4', 'Catechist'), ('5', 'Seminarian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Admin'), ('2', 'Priest'), ('3', 'Announcer'), ('4', 'Super Admin')], max_length=10, null=True),
        ),
    ]
