# Generated by Django 5.1 on 2024-09-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_priestprofile_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(default='sfbc/homily/default.jpg', upload_to='sfbc/homily/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.priestprofile')),
            ],
            options={
                'verbose_name_plural': 'homilies',
                'db_table': 'homily',
            },
        ),
    ]
