# Generated by Django 5.1 on 2024-09-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_homily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homily',
            old_name='date',
            new_name='entry_date',
        ),
    ]
