# Generated by Django 5.1 on 2024-09-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_homily_highlight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='priestprofile',
            name='position',
            field=models.CharField(choices=[('1', 'Parish Priest'), ('2', 'Assistant Parish Priest'), ('3', 'Priest in Residence'), ('4', 'Catechist'), ('5', 'Seminarian'), ('6', 'Chairman, Laity Council'), ('7', 'Chairman, Parish Pastoral Council'), ('8', 'Chairman, Parish Finance Council')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Priest'), ('3', 'Announcer'), ('4', 'Super Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='title',
            field=models.CharField(choices=[('1', 'Very Rev. Fr.'), ('2', 'Rev. Fr.'), ('3', 'Catechist'), ('4', 'Brother'), ('5', 'Deacon'), ('6', 'Rev.'), ('7', 'Mr.'), ('8', 'Mrs.'), ('9', 'Miss')], max_length=50),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, choices=[('1', 'Very Rev. Fr.'), ('2', 'Rev. Fr.'), ('3', 'Catechist'), ('4', 'Brother'), ('5', 'Deacon'), ('6', 'Rev.'), ('7', 'Mr.'), ('8', 'Mrs.'), ('9', 'Miss')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('1', 'Admin'), ('2', 'Priest'), ('3', 'Announcer'), ('4', 'Super Admin')], max_length=10, null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('othernames', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('position', models.CharField(blank=True, choices=[('1', 'Parish Priest'), ('2', 'Assistant Parish Priest'), ('3', 'Priest in Residence'), ('4', 'Catechist'), ('5', 'Seminarian'), ('6', 'Chairman, Laity Council'), ('7', 'Chairman, Parish Pastoral Council'), ('8', 'Chairman, Parish Finance Council')], max_length=50, null=True)),
                ('photo', models.ImageField(default='sfbc/profiles/default.jpg', upload_to='sfbc/profiles/')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profile',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('highlight', models.CharField(max_length=150)),
                ('entry_date', models.DateField()),
                ('event_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('venue', models.DateField()),
                ('photo', models.ImageField(default='sfbc/homily/default.jpg', upload_to='sfbc/homily/')),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adminprofile')),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
    ]
