# Generated by Django 5.1 on 2024-09-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_priestprofile_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='announcer',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='sfbc/events/default.jpg', upload_to='sfbc/events/'),
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('highlight', models.CharField(max_length=150)),
                ('entry_date', models.DateField()),
                ('photo', models.ImageField(default='sfbc/announcements/default.jpg', upload_to='sfbc/announcements/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adminprofile')),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
    ]
